import {screens} from './screens.mjs';
import {demoProducts} from './fixtures.mjs';
import {cssVariables,brand,light,dark,onColor,motion} from '../packages/tokens/index.mjs';
import {renderIcon,iconNames} from '../packages/icons/index.mjs';
import {renderArtwork,assets} from '../packages/assets/index.mjs';

// Isolated presentation fixtures. This studio never calls the restaurant API.
const ui={screen:'pos-sale',theme:'light',accent:brand.preview,state:'normal',category:'Tous',query:'',mode:'emporter',cart:[{id:'classic',qty:1},{id:'fries',qty:1},{id:'lemon',qty:1}],cartOpen:false,kdsTab:'new',channel:'Tous',modal:null,product:'classic',reduced:false,transparent:true,pin:'',allDay:true};
let sequence=0,toastTimer;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<span class="sm-icon" aria-hidden="true">${renderIcon(n)}</span>`;
const artwork=n=>`<span class="sm-art">${renderArtwork(n,'studio-'+(++sequence))}</span>`;
const euro=n=>(n/100).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';
const productBy=id=>demoProducts.find(p=>p.id===id)??demoProducts[0];
const total=()=>ui.cart.reduce((s,l)=>s+productBy(l.id).price*l.qty,0);
const selected=()=>screens.find(s=>s.id===ui.screen)??screens[0];
const blocked=()=>['loading','uncertain','offline','denied'].includes(ui.state);
const badge=(label,tone='neutral')=>`<span class="sm-badge sm-tone-${tone}">${esc(label)}</span>`;
function button(label,action='explain',options={}){
 return `<button type="button" class="sm-button sm-button--${options.tone??'secondary'} ${options.className??''}" data-action="${esc(action)}" ${options.value!==undefined?`data-value="${esc(options.value)}"`:''} ${options.disabled?'disabled':''} ${options.label?`aria-label="${esc(options.label)}" title="${esc(options.label)}"`:''}>${options.icon?icon(options.icon):''}${esc(label)}</button>`;
}
const iconButton=(name,label,action,value)=>button('',action,{icon:name,label,value,className:'sm-icon-button'});
const notice=(title,text,tone='info')=>`<div class="sm-notice sm-tone-${tone}" role="${tone==='danger'?'alert':'status'}">${icon(tone==='danger'||tone==='warning'?'warning':'info')}<div><strong>${esc(title)}</strong><div>${esc(text)}</div></div></div>`;
const input=(label,value='',type='text',hint='')=>`<div class="sm-field"><label>${esc(label)}<input type="${type}" value="${esc(value)}" placeholder="${esc(label)}" ${blocked()?'disabled':''}/></label>${hint?`<small>${esc(hint)}</small>`:''}</div>`;
const surface=(title,body,actions='')=>`<section class="sm-surface"><header class="sm-surface-head"><h2>${esc(title)}</h2>${actions}</header><div class="block-pad">${body}</div></section>`;
const heading=(title,sub='',actions='')=>`<div class="subhead"><div><h1>${esc(title)}</h1>${sub?`<p>${esc(sub)}</p>`:''}</div>${actions}</div>`;
function smBrand(){
 const id='sm-'+(++sequence);return `<div class="sm-brand"><svg viewBox="0 0 32 32" aria-hidden="true"><defs><mask id="${id}"><rect width="32" height="32" fill="white"/><path d="M16.9 8.6 12.5 16.4h3l-1 6.2 4.8-7.6h-3Z" fill="black"/></mask></defs><g mask="url(#${id})"><path d="M8.2 1.6h15.6q3.2 0 3.2 3.2v25l-2.7-1.7-2.7 1.7-2.7-1.7-2.7 1.7-2.7-1.7-2.7 1.7-2.7-1.7L5 29.8v-25q0-3.2 3.2-3.2Z" fill="none" stroke="currentColor" stroke-width="2.1" stroke-linejoin="round"/><path d="M8.6 11c0-8 14.8-8 14.8 0q0 1.4-1.4 1.4H10q-1.4 0-1.4-1.4Z M9.7 21.8h12.6q1.1 0 1.1 1.1c0 3.2-14.8 3.2-14.8 0q0-1.1 1.1-1.1Z" fill="currentColor"/><rect x="8.6" y="13.5" width="14.8" height="7" rx="2.2" fill="#c9a15a"/></g></svg><div><strong>snack manager</strong><small>Restaurant · démonstration</small></div></div>`;
}
function stateStrip(){
 const messages={offline:['Connexion interrompue','Les données visibles ne sont pas une confirmation de fraîcheur. Conserver la file et la reprise existantes.','warning'],uncertain:['Résultat à vérifier','Ne créez pas une seconde opération. La vérification réutilise l’intention existante.','warning'],loading:['Chargement','La surface conserve sa place pendant la lecture.','info'],stale:['Données à actualiser','La dernière lecture a vieilli. Ne la présentez pas comme du temps réel.','warning'],denied:['Accès restreint','Cette action dépend du rôle et des capacités du restaurant.','danger'],empty:['Aucun résultat','Cet état vide ne remplace pas une erreur de chargement.','info']};
 return messages[ui.state]?`<div class="state-strip">${notice(...messages[ui.state])}</div>`:'';
}
function toolbar(){
 const groups=[...new Set(screens.map(s=>s.family))];return `<header class="studio-bar"><div class="studio-brand">${icon('grid')}<span>Studio UI</span></div><label class="sr-only" for="screen-select">Interface</label><select id="screen-select">${groups.map(g=>`<optgroup label="${esc(g)}">${screens.filter(s=>s.family===g).map(s=>`<option value="${s.id}" ${ui.screen===s.id?'selected':''}>${esc(s.title)}</option>`).join('')}</optgroup>`).join('')}</select><label class="sr-only" for="state-select">État de la maquette</label><select id="state-select">${[['normal','État nominal'],['offline','Hors connexion'],['uncertain','Opération incertaine'],['loading','Chargement'],['stale','Données anciennes'],['denied','Accès restreint'],['empty','État vide']].map(([v,l])=>`<option value="${v}" ${ui.state===v?'selected':''}>${l}</option>`).join('')}</select><div class="studio-controls"><span class="studio-caption">Maquettes · données fictives</span>${iconButton(ui.theme==='dark'?'sun':'moon',ui.theme==='dark'?'Passer au thème clair':'Passer au thème sombre','theme')}${button(ui.accent===brand.preview?'Mandarine':'Laiton SM','accent')}${button(ui.reduced?'Mouvements réduits':'Mouvements','motion')}${iconButton('info','Source et périmètre','source')}</div></header>`;
}
function side(family){
 let entries=family==='Restaurant'?screens.filter(s=>s.family==='Restaurant'&&s.group&& !s.id.includes('admin-loyalty-')):family==='Plateforme'?screens.filter(s=>s.family==='Plateforme'):family==='KDS'?screens.filter(s=>['kds-board','kds-settings'].includes(s.id)):screens.filter(s=>['pos-sale','pos-service','pos-settings'].includes(s.id));
 let group='',nav='';for(const entry of entries){if(entry.group&&entry.group!==group){group=entry.group;nav+=`<div class="side-label">${esc(group)}</div>`;}const title=entry.id==='pos-settings'?'Réglages':entry.title;const ic=entry.icon??(entry.id==='pos-sale'?'pos':entry.id==='pos-service'?'orders':'settings');nav+=`<div class="side-nav"><button type="button" data-action="screen" data-value="${entry.id}" class="${ui.screen===entry.id?'active':''}">${icon(ic==='home'?'store':ic)}<span>${esc(title)}</span></button></div>`;}
 return `<aside class="side">${smBrand()}${nav}<div class="side-foot">${icon('shield')} <strong>Présentation uniquement</strong><p>Aucun appel API.<br>Fonctions métier inchangées.</p></div></aside>`;
}
function shell(content,family=selected().family){return `<div class="app-shell">${side(family)}<div class="app-main"><header class="app-top"><div class="crumb"><span>${family==='Plateforme'?'Snack Manager':'Restaurant démo'}</span>${icon('chevron')}<b>${esc(selected().title)}</b></div><div class="top-tools">${badge('Démonstration')}${button('Préférences','screen',{value:family==='POS'?'pos-settings':family==='KDS'?'kds-settings':'system-tokens',icon:'settings'})}</div></header>${stateStrip()}${content}</div></div>`;}
const categories=[['Tous','grid'],['Burgers','burger'],['Wraps','wrap'],['Bowls','bowl'],['À-côtés','fries'],['Boissons','cup'],['Desserts','dessert']];
const filtered=()=>demoProducts.filter(p=>(ui.category==='Tous'||ui.category===p.category)&&p.name.toLocaleLowerCase('fr').includes(ui.query.toLocaleLowerCase('fr')));
function search(){return `<div class="search-wrap">${icon('search')}<label class="sr-only" for="product-search">Rechercher un produit</label><input id="product-search" type="search" placeholder="Rechercher un produit…" value="${esc(ui.query)}"/></div>`;}
function categoryBar(){return `<div class="categories" role="group" aria-label="Catégories">${categories.map(([name,ic])=>`<button type="button" class="category ${ui.category===name?'active':''}" data-action="category" data-value="${name}" aria-pressed="${ui.category===name}">${icon(ic)}${name}</button>`).join('')}</div>`;}
function productsGrid(){
 if(ui.state==='empty')return empty('Aucun produit dans cette vue','Changez de catégorie ou effacez la recherche.');
 if(ui.state==='loading')return '<div class="sm-skeleton" aria-label="Chargement des produits" role="status"><span></span><span></span><span></span></div>';
 const rows=filtered();return rows.length?`<div class="product-grid">${rows.map(p=>`<button type="button" class="sm-product" data-action="product" data-value="${p.id}" aria-label="${esc(p.name)}, ${euro(p.price)}, configurer"><span class="sm-product-media">${artwork(p.art)}</span><span class="sm-product-copy"><strong>${esc(p.name)}</strong><span>${esc(p.description)}</span><span class="sm-product-price">${euro(p.price)}${icon('plus')}</span></span></button>`).join('')}</div>`:empty('Aucun produit trouvé','La recherche peut être modifiée sans perdre le ticket.');
}
function empty(title,description){return `<div class="sm-empty">${icon('box')}<h2>${esc(title)}</h2><p>${esc(description)}</p></div>`;}
function cart(){return `<aside class="sm-ticket"><header><div class="row between"><h2>Ticket</h2>${button('En attente','park',{className:'sm-button--quiet'})}</div><div class="ticket-meta"><span>Client de passage</span>${badge('Brouillon')}</div><div class="sm-segmented" role="group" aria-label="Mode de commande">${[['surplace','Sur place'],['emporter','À emporter'],['tel','Téléphone']].map(([v,l])=>`<button type="button" data-action="order-mode" data-value="${v}" class="${ui.mode===v?'active':''}" aria-pressed="${ui.mode===v}">${l}</button>`).join('')}</div></header><div class="sm-ticket-lines">${ui.mode==='tel'?`<div class="stack">${input('Nom du client')}${input('Téléphone','','tel')}${input('Créneau','','time')}</div>`:''}${ui.cart.length?ui.cart.map(l=>{const p=productBy(l.id);return `<article class="ticket-item">${artwork(p.art)}<div class="grow"><h3>${esc(p.name)}</h3><small>Recette classique</small><div class="row between"><div class="sm-stepper">${iconButton('minus','Diminuer '+p.name,'decrement',p.id)}<output>${l.qty}</output>${iconButton('plus','Augmenter '+p.name,'increment',p.id)}</div><strong class="tabular">${euro(p.price*l.qty)}</strong></div></div></article>`;}).join(''):empty('Votre ticket est vide','Choisissez un produit dans la carte.')}</div><footer><div class="row">${button('Note','note',{icon:'note',tone:'quiet',className:'grow'})}${button('Fidélité','loyalty',{icon:'gift',tone:'quiet',className:'grow'})}</div><div class="sm-total sm-total--main"><span>Total TTC</span><strong>${euro(total())}</strong></div>${ui.mode==='tel'?button('Confirmer le créneau','explain',{tone:'primary',disabled:blocked()||!ui.cart.length}):`<div class="row">${button('Espèces','payment',{icon:'cash',disabled:blocked()||!ui.cart.length,className:'grow'})}${button('Carte','payment',{icon:'card',tone:'primary',disabled:blocked()||!ui.cart.length,className:'grow'})}</div>${button('Titre-restaurant','payment',{tone:'quiet',disabled:blocked()||!ui.cart.length})}`}<small>Maquette : aucun encaissement n’est exécuté.</small></footer></aside>`;}
function pos(){return shell(`<div class="pos-layout ${ui.cartOpen?'cart-open':''}"><section class="pos-catalog">${heading('Caisse','La carte à portée de main. Le ticket reste visible.',button('Vider','clear',{icon:'close'}))}${search()}${categoryBar()}<div class="catalog-heading"><h2>${ui.category==='Tous'?'À la carte':esc(ui.category)}</h2><small>${filtered().length} produits · démo</small></div>${productsGrid()}</section>${cart()}</div>${button(ui.cartOpen?'Revenir à la carte':`Voir le ticket · ${euro(total())}`,'cart',{tone:'primary',className:'mobile-cart',icon:ui.cartOpen?'back':'bag'})}`,'POS');}
const tickets=[{number:128,status:'new',channel:'En ligne',mode:'À emporter',time:'03:24',items:[['2','Classic Smash','Sans oignons'],['1','Frites dorées','']],note:'Serviettes supplémentaires'},{number:127,status:'new',channel:'Caisse',mode:'Sur place',time:'05:10',items:[['1','Wrap du Chef','Sauce au choix'],['1','Cola 33 cl','']]},{number:125,status:'preparing',channel:'Caisse',mode:'À emporter',time:'11:08',items:[['2','Double Smash',''],['2','Frites dorées','']],note:'Sauces à part'},{number:126,status:'preparing',channel:'Téléphone',mode:'Retrait 19:30',time:'08:47',items:[['1','Bowl Croustillant',''],['1','Tiramisu','']]},{number:124,status:'ready',channel:'En ligne',mode:'À emporter',time:'13:02',items:[['1','Crispy Chicken',''],['1','Citronnade maison','']]}];
const statusLabels={new:'Nouveau',preparing:'En préparation',ready:'Prêt'},statusTone={new:'danger',preparing:'warning',ready:'success'};
function kds(){
 const rows=ui.state==='empty'?[]:tickets.filter(t=>ui.channel==='Tous'||ui.channel===t.channel);
 const pendingSummary=new Map();for(const t of rows.filter(t=>t.status!=='ready'))for(const [qty,name] of t.items)pendingSummary.set(name,(pendingSummary.get(name)??0)+Number(qty));
 const summary=[...pendingSummary].map(([name,qty])=>`<span>${qty} × ${esc(name)}</span>`).join('')||'<span>Aucun article à lancer</span>';
 return `<div class="kds-shell"><header class="kds-head"><div class="row">${smBrand()}<h1>Cuisine</h1></div><div class="row">${badge('Démonstration')}${iconButton('sound','Alerte sonore','explain')}${iconButton('settings','Réglages cuisine','screen','kds-settings')}</div></header>${stateStrip()}<div class="kds-toolbar"><div class="sm-action-row">${['Tous','Caisse','En ligne','Téléphone'].map(l=>button(l,'channel',{value:l,className:ui.channel===l?'sm-button--primary':''})).join('')}</div>${button('À lancer','allday',{icon:'menu'})}</div><div class="sm-segmented kds-tabs" role="group" aria-label="Statut cuisine">${Object.entries(statusLabels).map(([v,l])=>`<button type="button" data-action="kds-tab" data-value="${v}" class="${ui.kdsTab===v?'active':''}">${v==='preparing'?'En prépa':l} · ${rows.filter(t=>t.status===v).length}</button>`).join('')}</div>${ui.allDay?`<div class="allday"><strong>À lancer</strong>${summary}</div>`:''}<div class="kds-grid">${Object.entries(statusLabels).map(([status,label])=>`<section class="kds-col ${ui.kdsTab===status?'current':''}"><div class="kds-col-header"><h2>${label}</h2>${badge(rows.filter(t=>t.status===status).length,statusTone[status])}<small>${status==='new'?'À accepter':status==='preparing'?'En cours':'À remettre'}</small></div>${rows.filter(t=>t.status===status).map(t=>`<article class="sm-kitchen-ticket sm-kitchen-ticket--${statusTone[status]}"><header><h3>#${t.number}</h3>${badge(t.time,statusTone[status])}</header><p>${t.channel} · ${t.mode}</p><ul>${t.items.map(([q,n,d])=>`<li><strong>${q}×</strong><span><b>${n}</b>${d?`<small>${d}</small>`:''}</span></li>`).join('')}</ul>${t.note?`<p class="sm-kitchen-note">${t.note}</p>`:''}${status==='ready'?`<div class="sm-badge sm-tone-success">En attente de prise en charge</div>`:button(status==='new'?'Accepter':'Marquer prête','advance',{value:t.number,disabled:blocked()})}</article>`).join('')||empty('Aucune commande','Les tickets de ce statut apparaîtront ici.')}</section>`).join('')}</div></div>`;
}
function mobile(body,active,family=selected().family){
 const nav=family==='Livreur'?[['courier-tour','Tournée','orders'],['courier-map','Carte','pin'],['courier-history','Historique','clock'],['courier-account','Compte','user']]:[['online-menu','Carte','grid'],['online-menu','Rechercher','search'],['online-orders','Commandes','orders'],['loyalty-card','Fidélité','gift']];
 return `${stateStrip()}<div class="mobile-surface"><header class="mobile-top">${smBrand()}${iconButton('user','Mon compte','screen',family==='Livreur'?'courier-account':'online-account')}</header><main class="mobile-content">${body}</main><nav class="mobile-bottom" aria-label="Navigation de l’application">${nav.map(([id,label,ic],index)=>`<button type="button" data-action="${index===1&&family!=='Livreur'?'search-tab':'screen'}" data-value="${id}" class="${active===id&&index!==1?'active':''}" ${active===id&&index!==1?'aria-current="page"':''}>${icon(ic)}<span>${label}</span></button>`).join('')}</nav></div>`;
}
function storefront(){return mobile(`${heading('Qu’est-ce qui vous fait envie ?','La carte de démonstration du studio.')}<div class="mobile-hero"><div><strong>Vos classiques,<br>à votre façon.</strong><p>Personnalisez votre sélection.</p></div>${artwork('burger')}</div>${search()}${categoryBar()}${productsGrid()}${button('Voir mon panier · '+euro(total()),'screen',{value:'online-checkout',tone:'primary',icon:'bag'})}`,'online-menu');}
function cartLines(){return `<ul class="flow-list">${ui.cart.map(l=>`<li>${artwork(productBy(l.id).art)}<div class="grow"><strong>${l.qty}× ${esc(productBy(l.id).name)}</strong><small>${esc(productBy(l.id).description)}</small></div><b class="tabular">${euro(productBy(l.id).price*l.qty)}</b></li>`).join('')}</ul>`;}
function checkout(){return mobile(`${heading('Votre commande','Contrôlez votre sélection avant de continuer.')}<div class="sm-segmented"><button type="button" data-action="checkout-mode" data-value="pickup" class="${ui.checkoutMode!=='delivery'?'active':''}">Retrait</button><button type="button" data-action="checkout-mode" data-value="delivery" class="${ui.checkoutMode==='delivery'?'active':''}">Livraison</button></div>${cartLines()}${ui.checkoutMode==='delivery'?surface('Adresse de livraison',`<div class="stack">${input('Adresse')}${input('Code postal')}${input('Ville')}${button('Vérifier l’adresse','explain',{disabled:blocked(),className:'wide'})}</div>`):surface('Votre créneau',`<div class="stack">${input('Jour','2026-09-12','date')}${input('Heure','19:30','time')}<small>La disponibilité doit être relue par le parcours existant.</small></div>`)}${input('Votre nom')}${input('Téléphone','','tel')}<div class="sm-total sm-total--main"><span>Total articles</span><strong>${euro(total())}</strong></div>${notice('Paiement hors maquette','Le formulaire du prestataire et les éventuels frais restent pilotés par le checkout réel.')} ${button('Continuer','explain',{tone:'primary',disabled:blocked()})}`,'online-orders');}
function tracking(){return mobile(`${heading('Commande #128','Exemple de suivi, sans commande réelle.')}<div class="mobile-hero"><div><strong>En préparation</strong><p>Le statut dépend de la confirmation du restaurant.</p></div>${artwork('bag' in Object.fromEntries(assets.map(a=>[a.id,1]))?'bag':'burger')}</div><ol class="timeline">${[['check','Commande reçue','Le restaurant a reçu la commande.'],['kitchen','En préparation','Votre sélection est en cours de préparation.'],['bag','Prête à retirer','Cette étape attend une confirmation.']].map(([ic,l,d])=>`<li>${icon(ic)}<div><b>${l}</b><small>${d}</small></div></li>`).join('')}</ol>${cartLines()}${button('Voir les détails','explain',{icon:'orders'})}${button('Commander à nouveau','screen',{value:'online-menu',tone:'quiet'})}`,'online-orders');}
function loyalty(){return mobile(`${heading('Ma fidélité','Votre carte, vos avantages.')}<section class="sm-loyalty-pass loyalty-pass-small"><div class="row between"><p>Restaurant démo</p>${icon('gift')}</div><strong>130 <span style="font-size:20px;letter-spacing:0">points</span></strong><p>Solde fictif · réservé à la présentation</p><div class="progress-track"><span></span></div><p>Exemple : prochain palier à 200 points</p></section>${button('Scanner mon ticket','screen',{value:'loyalty-scan',tone:'primary',icon:'camera'})}<div class="row between"><h2>Vos récompenses</h2>${badge('Exemples')}</div><div class="reward">${artwork('tiramisu')}<div class="grow"><h3>Un dessert</h3><p>Exemple de récompense · 200 points</p></div>${icon('chevron')}</div><div class="reward">${artwork('fries')}<div class="grow"><h3>Une portion de frites</h3><p>Exemple de récompense · 150 points</p></div>${icon('chevron')}</div>${notice('Aucun avantage réel','Les paliers et le solde ci-dessus sont des fixtures. La maquette ne crédite ni ne dépense de points.')} ${button('Afficher ma carte','qr',{icon:'qr'})}`,'loyalty-card','Fidélité');}
function scanner(){return mobile(`${heading('Scanner mon ticket','Cadrez le code du ticket, puis attendez la réponse.')}<div class="scan-target">${icon('qr')}<p>Zone de cadrage<br>Caméra inactive dans la maquette</p></div>${notice('La lecture n’est pas le succès','Un QR reconnu n’ajoute pas de points avant confirmation du serveur.')} ${button('Voir le retour de lecture','scan-result',{tone:'primary',icon:'camera'})}${button('Revenir à ma carte','screen',{value:'loyalty-card',tone:'quiet'})}`,'loyalty-card','Fidélité');}
function courier(){return mobile(`${heading('Votre tournée','Les missions affectées à cet accès.')}<div class="mini-stats"><div><b>2</b><span>Missions démo</span></div><div><b>1</b><span>Prête au départ</span></div></div>${[128,126].map((n,idx)=>surface('Commande #'+n,`<div class="stack"><div>${badge(idx?'En préparation':'Prête au départ',idx?'warning':'success')}</div><p class="address">${idx?'12 avenue Exemple':'8 rue Démonstration'}<br>76000 · Ville démo</p><div class="row between"><small>Adresse fictive</small>${badge('Paiement confirmé · fixture')}</div><div class="sm-action-row">${button(idx?'En préparation':'Démarrer','explain',{tone:idx?'secondary':'primary',disabled:idx||blocked(),icon:idx?'clock':'arrow'})}${iconButton('phone','Contacter le client','explain')}${iconButton('pin','Ouvrir l’itinéraire','screen','courier-map')}</div></div>`)).join('')}`,'courier-tour','Livreur');}
function route(){return mobile(`${heading('Vos arrêts','Adresses de démonstration. Aucun suivi GPS simulé.')}<div class="route-steps">${[['Départ','Restaurant démo'],['Commande #128','8 rue Démonstration · 76000'],['Commande #126','12 avenue Exemple · 76000']].map(([t,a],i)=>`<div class="route-step"><span>${i+1}</span><div><b>${t}</b><small>${a}</small></div></div>`).join('')}</div>${notice('Itinéraire externe','La vue ouvre l’application de navigation choisie dans le parcours réel. Pas de distance ou d’optimisation inventée.')} ${button('Choisir l’application de navigation','navigation',{icon:'pin',tone:'primary'})}${button('Confirmer une remise','handoff',{icon:'qr',disabled:blocked()})}${button('Signaler un incident','explain',{tone:'quiet',icon:'warning'})}`,'courier-map','Livreur');}
function customerOrders(){const courierMode=selected().family==='Livreur';return mobile(`${heading(courierMode?'Historique':'Commandes',courierMode?'Lecture des remises enregistrées.':'Distinguez cet appareil et votre compte.')}<div class="sm-segmented"><button type="button" class="active" data-action="explain">${courierMode?'Terminées':'Cet appareil'}</button><button type="button" data-action="explain">${courierMode?'Filtrer':'Mon compte'}</button></div>${[124,121,119].map((n,i)=>surface('Commande #'+n,`<div class="stack"><div class="row between">${badge(courierMode?'Livrée':'Terminée','success')}<small>Historique fictif</small></div><p>${i?'Double Smash · Frites dorées':'Classic Smash · Citronnade maison'}</p><div class="row between"><b class="tabular">${i?'15,40 €':'12,80 €'}</b>${button(courierMode?'Détails':'Recommander',courierMode?'explain':'screen',{value:'online-menu',icon:'arrow'})}</div></div>`)).join('')}`,courierMode?'courier-history':'online-orders',courierMode?'Livreur':'Commande');}
function account(){return mobile(`${heading('Mon compte','Votre identité et vos accès.')}<div class="row"><div class="avatar">AD</div><div><h2>Compte de démonstration</h2><small>Aucune donnée client réelle</small></div></div>${surface('Mes informations',`<div class="stack">${input('Nom affiché','Compte démo')}${input('Adresse e-mail','demo@example.test','email')}${button('Enregistrer','explain',{disabled:blocked()})}</div>`)}${surface('Sécurité',`<div class="stack">${button('Clé d’accès','explain',{icon:'lock'})}${button('Options de récupération','explain',{icon:'shield'})}</div>`)}${button('Mes commandes','screen',{value:'online-orders',icon:'orders'})}${button('Ma fidélité','screen',{value:'loyalty-card',icon:'gift'})}${button('Me déconnecter','explain',{tone:'quiet',icon:'logout'})}`,'online-account');}
function preferences(){
 const isKds=selected().family==='KDS',isCourier=selected().family==='Livreur';const body=`${heading(selected().title,'Réglages locaux : ils ne changent pas les droits du compte.')} ${surface('Apparence',`<div class="stack"><div><h3>Thème</h3><div class="sm-segmented" style="margin-top:14px"><button type="button" data-action="theme-light" class="${ui.theme==='light'?'active':''}">Clair</button><button type="button" data-action="theme-dark" class="${ui.theme==='dark'?'active':''}">Sombre</button></div></div><div class="toggle-row"><div><h3>Réduire les mouvements</h3><p>Transitions discrètes, sans animation décorative.</p></div><input type="checkbox" id="motion-check" aria-label="Réduire les mouvements" ${ui.reduced?'checked':''}/></div><div class="toggle-row"><div><h3>Réduire la transparence</h3><p>Fonds opaques pour une meilleure lisibilité.</p></div><input type="checkbox" id="transparency-check" aria-label="Réduire la transparence" ${!ui.transparent?'checked':''}/></div></div>`)}${surface(isCourier?'Navigation':isKds?'Lecture en cuisine':'Disposition de caisse',isCourier?button('Plans, Google Maps ou Waze','navigation',{icon:'pin'}):`<div class="stack"><div class="sm-segmented">${(isKds?['Confort','Dense']:['A','B','C']).map((l,i)=>`<button type="button" class="${i===0?'active':''}" data-action="explain">${l}</button>`).join('')}</div><small>${isKds?'Conserver les seuils 10 / 15 minutes et les préférences existantes.':'La migration doit garder les trois dispositions et le côté du ticket.'}</small></div>`)}${button('Retour', 'screen',{value:isKds?'kds-board':isCourier?'courier-tour':'pos-sale',icon:'back'})}`;
 return isCourier?mobile(body,'courier-account','Livreur'):shell(`<main class="section-pad"><div style="max-width:800px" class="stack">${body}</div></main>`,isKds?'KDS':'POS');
}
function auth(){const pairing=ui.screen==='pos-pairing',pin=['pos-pin','kds-pin'].includes(ui.screen),courierMode=ui.screen==='courier-access';return `${stateStrip()}<main class="auth"><section class="auth-card">${smBrand()}<div>${heading(selected().title,pairing?'Entrez le code d’appairage de l’appareil.':pin?'Identifiez-vous avec votre code équipier.':courierMode?'Utilisez l’accès fourni par le restaurant.':'Connectez-vous à votre espace.')}</div>${pin?`<div class="pin-dots" aria-label="${ui.pin.length} chiffres saisis">${[0,1,2,3].map(i=>`<span class="${i<ui.pin.length?'filled':''}"></span>`).join('')}</div><div class="keypad">${['1','2','3','4','5','6','7','8','9','Effacer','0','Entrer'].map(n=>button(n,'pin',{value:n})).join('')}</div>`:`<div class="stack">${input(pairing?'Code à six caractères':courierMode?'Identifiant d’accès':'Adresse e-mail','',pairing||courierMode?'text':'email')}${pairing?'':input('Mot de passe','','password')}${button(pairing?'Appairer':'Se connecter','explain',{tone:'primary',disabled:blocked()})}</div>`}<small>Maquette : ne saisissez pas de vrais identifiants.</small></section></main>`;}
function payment(){return shell(`<main class="section-pad"><div style="max-width:640px;margin:auto" class="stack">${heading('Encaisser une commande','L’encaissement existant reste la seule source de vérité.')} ${surface('Commande #128',`<div class="stack">${cartLines()}<div class="sm-total sm-total--main"><span>Reste à régler · exemple</span><strong>${euro(total())}</strong></div><div class="sm-segmented"><button type="button" data-action="explain" class="active">Carte</button><button type="button" data-action="explain">Espèces</button><button type="button" data-action="explain">Titre-restaurant</button></div>${input('Montant reçu · exemple',euro(total()))}${notice('Aucune transaction','Cet écran montre la présentation. Les validations et la reprise restent dans service-payment et le journal existants.')} ${button('Confirmer','explain',{tone:'primary',disabled:blocked()})}${button('Retour à la caisse','screen',{value:'pos-sale',tone:'quiet'})}</div>`)}</div></main>`,'POS');}
function metrics(platform=false){return `<div class="metric-row">${(platform?[['Restaurants','24','Exemple de parc'],['MRR','—','Donnée réelle non chargée'],['À traiter','8','Exemple de file'],['Dossiers','6','Exemple de production']]:[['Chiffre d’affaires','1 248,60 €','Exemple de journée'],['Commandes','86','Tous canaux · exemple'],['Panier moyen','14,52 €','Valeur illustrative'],['En cours','5','Exemple de service']]).map(([a,b,c])=>`<div class="metric"><span>${a}</span><strong>${b}</strong><small>${c}</small></div>`).join('')}</div>`;}
function chart(){return `<div class="chart-panel"><div class="row between"><h2>Activité du service</h2><small>Données fictives</small></div><div class="bars" role="img" aria-label="Graphique illustratif d’activité, valeurs non réelles">${[22,46,74,52,92,65,42,28].map((v,i)=>`<div style="--height:${v}%"><small>${12+i} h</small></div>`).join('')}</div></div>`;}
function ordersTable(){return dataTable(['Commande','Canal','Statut','Total','Action'],tickets.map(t=>['#'+t.number,t.channel,statusLabels[t.status],t.number%2?'15,40 €':'12,80 €','Consulter']),true);}
function dataTable(columns,rows,actions=false){
 const body=ui.state==='empty'?[]:rows;
 return `<div class="sm-table-scroll" tabindex="0" role="region" aria-label="${esc(selected().title)}"><table><caption>${esc(selected().title)} · échantillon de démonstration</caption><thead><tr>${columns.map(c=>`<th scope="col">${esc(c)}</th>`).join('')}</tr></thead><tbody>${body.map((r,i)=>`<tr>${r.map((c,j)=>`<td>${actions&&j===r.length-1?button(String(c),'detail',{value:i}):j===0?`<strong>${esc(c)}</strong>`:String(c).includes('préparation')||c==='Actif'||c==='Disponible'?badge(c,c==='Actif'||c==='Disponible'?'success':'warning'):esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>${body.length?'':empty('Aucun résultat','Ajustez les filtres ou revenez plus tard.')}</div>`;
}
function tableTools(){return `<div class="table-tools"><label class="sr-only" for="table-search">Rechercher dans la liste</label><input id="table-search" placeholder="Rechercher…" type="search"/><div class="sm-action-row">${button('Filtres','filters',{icon:'filter'})}${button('Exporter','export',{icon:'download'})}</div></div>`;}
function dashboard(platform=false){return `${metrics(platform)}<div class="grid-two">${surface('Vue de la journée',chart())}${surface(platform?'File du jour':'Commandes en cours',`<ul class="flow-list">${tickets.slice(0,4).map(t=>`<li><div class="avatar">#${t.number}</div><div class="grow"><strong>${t.channel}</strong><small>${t.mode} · ${t.time}</small></div>${badge(statusLabels[t.status],statusTone[t.status])}</li>`).join('')}</ul>`)}</div><div style="margin-top:24px">${ordersTable()}</div>`;}
function adminGeneric(){
 const s=selected(),kind=s.kind,platform=s.family==='Plateforme';let body='';
 if(kind==='dashboard')body=dashboard(platform);
 else if(kind==='orders')body=`${tableTools()}<div class="page-tabs">${['Toutes','Nouveau','En préparation','Prêt','Terminées'].map((t,i)=>button(t,'table-filter',{value:t,className:i?'':'active'})).join('')}</div>${ordersTable()}`;
 else if(kind==='dispatch')body=`<div class="grid-two">${surface('À affecter',`<div class="stack">${[128,126].map(n=>`<div class="row between"><div><h3>Commande #${n}</h3><small>Prête · paiement confirmé · fixture</small></div>${button('Affecter','assign',{value:n,disabled:blocked()})}</div>`).join('')}</div>`)}${surface('Livreurs',`<ul class="flow-list">${['Livreur A','Livreur B'].map((n,i)=>`<li><div class="avatar">${i+1}</div><div class="grow"><strong>${n}</strong><small>${i?'1 mission en cours':'Disponible'}</small></div>${badge('Accès actif','success')}</li>`).join('')}</ul>`)}</div><div style="margin-top:24px">${tableTools()}${ordersTable()}</div>`;
 else if(kind==='catalog-admin')body=`${tableTools()}<div class="grid-two">${surface('Produits',`<ul class="flow-list">${demoProducts.slice(0,6).map(p=>`<li>${artwork(p.art)}<div class="grow"><strong>${p.name}</strong><small>${p.category} · ${euro(p.price)}</small></div>${iconButton('edit','Modifier '+p.name,'product',p.id)}</li>`).join('')}</ul>`)}${surface('Fiche produit',`<div class="stack"><div class="sheet-product-art">${artwork('burger')}</div>${input('Nom','Classic Smash')}${input('Prix · centimes','890','number')}${input('Catégorie','Burgers')}${button('Variantes et options','product',{value:'classic',icon:'plus'})}${button('Enregistrer','explain',{tone:'primary',disabled:blocked()})}<small>Ne modifier ni les médias sélectionnés, ni les règles de configuration depuis le kit.</small></div>`)}</div>`;
 else if(kind==='settings')body=`<div class="settings-layout">${surface(s.title,`<form class="stack" data-demo-form><div class="form-grid">${(s.fields?.length?s.fields:['Nom','Description']).map((x,i)=>input(x,i===0?'Démonstration':'')).join('')}</div>${notice('Données de présentation','Les champs exacts, leur validation et les droits seront conservés depuis le formulaire existant.')}<div class="sm-action-row">${button('Enregistrer','explain',{tone:'primary',disabled:blocked()})}${button('Annuler','explain')}</div></form>`)}${surface('Aperçu',`<div class="settings-preview"><div class="mobile-hero"><strong>Restaurant démo</strong>${artwork('burger')}<p>Votre identité, sur les surfaces existantes.</p></div></div>`)}</div>`;
 else if(kind==='hours')body=`${surface('Ouverture de l’établissement',`<div class="stack">${['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche'].map((d,i)=>`<div class="toggle-row"><h3>${d}</h3><div class="row"><span>${i===0?'Fermé':'11:30 — 14:30 / 18:00 — 22:30'}</span>${iconButton('edit','Modifier '+d,'detail',i)}</div></div>`).join('')}</div>`)}<div style="margin-top:24px">${surface('Créneaux',`<div class="form-grid">${input('Intervalle en minutes','10','number')}${input('Capacité par créneau','4','number')}</div><div class="sm-action-row" style="margin-top:20px">${button('Enregistrer','explain',{tone:'primary',disabled:blocked()})}${button('Ajouter une fermeture','detail',{icon:'plus'})}</div>`)}</div>`;
 else if(kind==='devices')body=`<div class="tile-list">${[['pos','Caisse comptoir'],['kitchen','Écran cuisine'],['print','Imprimante tickets']].map(([ic,title])=>`<section class="sm-surface device-card"><div class="device-icon">${icon(ic)}</div><h2>${title}</h2>${badge('Exemple d’appareil','info')}<small>La maquette ne teste pas la connexion matérielle.</small>${button('Gérer','detail',{icon:'settings'})}</section>`).join('')}</div><div style="margin-top:24px">${button('Appairer un appareil','screen',{value:'pos-pairing',tone:'primary',icon:'plus'})}</div>`;
 else if(kind==='planning')body=`${tableTools()}<div class="planning-scroll"><div class="planning-grid">${['Équipe','Lundi','Mardi','Mercredi','Jeudi','Vendredi'].map(t=>`<div><strong>${t}</strong></div>`).join('')}${['Équipier A','Équipier B','Équipier C','Équipier D'].map((n,i)=>`<div><strong>${n}</strong></div>${[0,1,2,3,4].map(j=>`<div>${(i+j)%4?`<span class="shift">${j%2?'18:00 — 22:00':'11:00 — 15:00'}</span>`:'Repos'}</div>`).join('')}`).join('')}</div></div><p class="muted" style="margin-top:18px">Planning fictif. Les heures et coûts réels restent soumis aux droits existants.</p>`;
 else if(kind==='stats')body=`${metrics()}${surface('Activité',chart())}<div style="margin-top:24px">${tableTools()}${dataTable(['Canal','Commandes','Chiffre d’affaires'],[['Caisse','60','840,00 €'],['En ligne','20','300,00 €'],['Téléphone','6','108,60 €']])}</div>`;
 else if(kind==='loyalty-admin')body=`<div class="page-tabs">${[['admin-fidelite','Vue d’ensemble'],['admin-loyalty-programme','Programme'],['admin-loyalty-recompenses','Récompenses'],['admin-loyalty-clients','Clients']].map(([v,l])=>button(l,'screen',{value:v,className:v===s.id?'active':''})).join('')}</div><div class="metric-row">${[['Membres','124'],['Visites','48'],['Récompenses','12'],['Programme','Actif']].map(([l,v])=>`<div class="metric"><span>${l}</span><strong>${v}</strong><small>Exemple uniquement</small></div>`).join('')}</div>${surface('Piloter la fidélité',`<div class="grid-two">${button('Programme','screen',{value:'admin-loyalty-programme',icon:'settings'})}${button('Récompenses','screen',{value:'admin-loyalty-recompenses',icon:'gift'})}${button('Clients','screen',{value:'admin-loyalty-clients',icon:'users'})}${button('Voir la carte client','screen',{value:'loyalty-card',icon:'qr'})}</div>`)}`;
 else if(kind==='rewards')body=`<div class="tile-list">${[['tiramisu','Dessert'],['fries','Frites'],['burger','Burger']].map(([a,l],i)=>`<section class="sm-surface device-card"><div class="sheet-product-art">${artwork(a)}</div><h2>${l}</h2><p>Exemple · ${150+i*50} points</p>${button('Modifier la récompense','detail',{disabled:blocked()})}</section>`).join('')}</div>`;
 else if(kind==='reviews')body=`${tableTools()}<div class="grid-two">${['Le service était agréable.','Commande préparée avec soin.'].map((t,i)=>surface('Avis fictif '+(i+1),`<div class="stack"><div class="row">${icon('star')}${icon('star')}${icon('star')}${icon('star')}${icon('star')}</div><p>${t}</p><small>Texte de maquette, pas un témoignage client.</small>${button('Répondre','detail',{disabled:blocked()})}</div>`)).join('')}</div>`;
 else if(kind==='site')body=`<div class="page-tabs">${['Identité','Accueil','Carte','Style avancé'].map((t,i)=>button(t,'table-filter',{value:t,className:i?'':'active'})).join('')}</div><div class="settings-layout">${surface('Identité du restaurant',`<div class="stack">${input('Nom','Restaurant démo')}${input('Accroche','Vos classiques, à votre façon.')}${input('Couleur de marque',ui.accent)}${button('Choisir un média','media',{icon:'grid'})}${button('Enregistrer le brouillon','explain',{tone:'primary',disabled:blocked()})}</div>`)}${surface('Aperçu non publié',`<div class="stack"><div class="mobile-hero"><div><strong>Restaurant démo</strong><p>Votre carte.</p></div>${artwork('burger')}</div>${button('Ouvrir la maquette client','screen',{value:'online-menu'})}<small>Une prévisualisation n’est pas une confirmation de publication.</small></div>`)}</div>`;
 else if(kind==='screens')body=`<div class="grid-two">${surface('Écran de salle',`<div class="screen-display">${artwork('double')}<div><strong>La carte<br>du moment.</strong><p>Scénographie de démonstration</p></div></div>${button('Modifier la présentation','detail',{icon:'edit'})}`)}${surface('Diffusion',`<div class="stack">${input('Nom de l’écran','Écran comptoir')}${input('Scénographie','Menu')}${button('Prévisualiser','explain',{icon:'tv'})}${button('Enregistrer','explain',{tone:'primary',disabled:blocked()})}</div>`)}</div>`;
 else if(kind==='billing')body=`<div class="grid-two">${surface(platform?'Suivi de facturation':'Mon abonnement',`<div class="stack"><h2>${platform?'Données de facturation':'Offre et échéance'}</h2><p class="muted">Les montants contractuels ne sont pas reproduits dans la maquette.</p>${badge('Compte de démonstration')}${button('Gérer','explain',{disabled:blocked()})}</div>`)}${surface('Documents',`<div class="stack"><div class="row between"><div><h3>Facture exemple</h3><small>Document non disponible dans le studio</small></div>${iconButton('download','Télécharger le document','explain')}</div>${notice('Lecture selon le rôle','La refonte conserve les droits existants, dont les accès comptables.')} </div>`)}</div>`;
 else if(kind==='pipeline')body=`<div class="kanban">${[['Nouveau','Restaurant exemple A','Restaurant exemple B'],['Contacté','Restaurant exemple C'],['Proposition','Restaurant exemple D']].map(([title,...names])=>`<section class="kanban-col"><h2>${title}</h2>${names.map(n=>`<article class="kanban-card"><h3>${n}</h3><p>Prospect fictif · prochaine action à définir</p><div class="row between">${badge('À suivre')}${button('Ouvrir','detail',{icon:'arrow'})}</div></article>`).join('')}</section>`).join('')}</div>`;
 else {
  const fields=s.fields?.length?s.fields:['Libellé','État','Détails'];
  const data=Array.from({length:6},(_,i)=>fields.map((f,j)=>j===0?`${s.title==='Stocks'?['Pain burger','Steak','Cheddar','Pommes de terre','Salade','Sauce'][i]:s.title==='Équipe'?'Équipier '+String.fromCharCode(65+i):'Exemple '+(i+1)}`:f==='Unité'?'kg':f.includes('Coût')?'3,20 €':f.includes('Stock')?'12,5':f==='Solde'?'130 points':f.includes('Rôle')?(i?'caisse':'gerant'):f.includes('visite')?'Aujourd’hui':f.includes('Consentement')?'Non renseigné':f.includes('Disponibilité')?'Disponible':f.includes('État')?'Actif':'—'));
  body=tableTools()+dataTable([...fields,'Action'],data.map(r=>[...r,'Détails']),true);
 }
 return shell(`<main class="section-pad">${heading(s.title,'Présentation de l’existant · données de démonstration',button(kind==='orders'?'Actualiser':'Actions','detail',{icon:kind==='orders'?'refresh':'dots',disabled:blocked()}))}${body}</main>`,platform?'Plateforme':s.family==='POS'?'POS':'Restaurant');
}
function components(){return shell(`<main class="section-pad">${heading('Composants','Les mêmes rôles visuels, des adaptateurs DOM et React Native.')}<div class="component-grid">${surface('Actions',`<div class="stack"><div class="sm-action-row">${button('Primaire','explain',{tone:'primary'})}${button('Secondaire','explain')}${button('Destructif','explain',{tone:'danger'})}</div>${button('Opération en cours','explain',{disabled:true})}<div class="row">${badge('Prêt','success')}${badge('En préparation','warning')}${badge('À vérifier','danger')}</div></div>`)}${surface('Formulaires',`<div class="stack">${input('Nom du produit','Classic Smash')}${input('Note de préparation')}<div class="sm-segmented"><button type="button" class="active" data-action="explain">Sur place</button><button type="button" data-action="explain">À emporter</button></div></div>`)}${surface('Retours d’état',`<div class="stack">${notice('Résultat à vérifier','Pas de nouvelle intention avant réconciliation.','warning')}${notice('Action non autorisée','Le rôle ne permet pas cette opération.','danger')}</div>`)}${surface('Surcouches',`<div class="stack">${button('Fiche produit','product',{value:'classic',icon:'burger'})}${button('Feuille de confirmation','handoff',{icon:'qr'})}${button('Fenêtre avec formulaire','note',{icon:'note'})}</div>`)}</div></main>`,'POS');}
function assetsView(){return shell(`<main class="section-pad">${heading('Illustrations & icônes','Vraies ressources SVG halal-first, sans police ni SF Symbols redistribués.')}<div class="asset-grid">${assets.map(a=>`<article class="asset-cell">${artwork(a.id)}<strong>${esc(a.label)}</strong><code>${a.id}.svg</code></article>`).join('')}</div><div style="margin:36px 0 20px"><h2>Icônes · grille 24 × 24</h2></div><div class="icon-grid">${iconNames.map(n=>`<div class="icon-cell">${icon(n)}<span>${n}</span></div>`).join('')}</div></main>`,'POS');}
function tokensView(){const t=ui.theme==='dark'?dark:light;return shell(`<main class="section-pad">${heading('Tokens & matières','Rôles sémantiques, thème clair et sombre, accent de restaurant indépendant.')}<div class="asset-grid">${Object.entries(t).filter(([,v])=>v.startsWith('#')).map(([k,v])=>`<div class="asset-cell"><div class="swatch" style="background:${v};color:${onColor(v)}">${v}</div><strong>${k}</strong></div>`).join('')}</div><div style="margin-top:28px" class="grid-two">${surface('Typographie',`<div class="stack"><h1>Caisse & cuisine</h1><h2>Une hiérarchie claire</h2><p>Lecture confortable. Chiffres tabulaires : <b class="tabular">128 · 16,30 €</b></p><small>Polices système ; aucun fichier de police distribué.</small></div>`)}${surface('Mouvement',`<ul class="flow-list">${Object.entries(motion).filter(([,v])=>typeof v==='number').map(([k,v])=>`<li><strong class="grow">${k}</strong><span>${ui.reduced?0:v} ms</span></li>`).join('')}</ul>`)}</div></main>`,'POS');}
function content(){const s=selected();if(s.kind==='pos')return pos();if(s.kind==='kds')return kds();if(s.kind==='storefront')return storefront();if(s.kind==='checkout')return checkout();if(s.kind==='tracking')return tracking();if(s.kind==='loyalty')return loyalty();if(s.kind==='scanner')return scanner();if(s.kind==='courier')return courier();if(s.kind==='route')return route();if(s.kind==='customer-orders')return customerOrders();if(s.kind==='account')return account();if(s.kind==='prefs')return preferences();if(s.kind==='auth')return auth();if(s.kind==='payment')return payment();if(s.kind==='components')return components();if(s.kind==='assets')return assetsView();if(s.kind==='tokens')return tokensView();return adminGeneric();}
function modalContent(){
 const p=productBy(ui.product);let title='',body='',footer='';
 if(ui.modal==='product'){title=p.name;body=`<div class="sheet-product-art">${artwork(p.art)}</div><div class="row between"><p>${esc(p.description)}</p><strong class="sheet-product-price">${euro(p.price)}</strong></div><div><h3>Votre sauce · choix illustratif</h3><div class="choices" style="margin-top:12px">${['Signature','Blanche','Barbecue','Sans sauce'].map((n,i)=>`<label><input type="radio" name="sauce" value="${n}" ${i===0?'checked':''}/>${n}</label>`).join('')}</div></div><div class="sm-field"><label for="config-note">Note de préparation</label><textarea id="config-note" placeholder="Une précision pour la cuisine…"></textarea></div><small>Dans l’application, seuls les groupes et contraintes reçus du catalogue seront affichés.</small>`;footer=button('Ajouter au ticket','add',{value:p.id,tone:'primary',disabled:blocked()});}
 else if(ui.modal==='source'){title='Source & périmètre';body=`<p><strong>${esc(selected().title)}</strong></p><code style="overflow-wrap:anywhere">${esc(selected().source)}</code><p>Référence : develop · 2c879899adc0e7c3b98817ef76cf026ea5d22bf8.</p>${notice('Maquette indépendante','Aucun service, donnée client, paiement ou contrôle métier n’est remplacé. Les composants React sont livrés séparément.')}<p>Le contraste et les cibles tactiles ont été renforcés par rapport à l’aperçu d’origine. L’accent mandarine est une option du studio, pas une nouvelle marque imposée au restaurant.</p>`;}
 else if(ui.modal==='handoff'){title='Confirmer la remise';body=`${input('Code de remise')}<div class="qr-slot">${icon('qr')}<strong>Scanner le QR du client</strong><small>Caméra inactive · code illustratif non utilisable</small></div>${notice('Une étape explicite','Un QR lu ne confirme pas la livraison. Le succès exige le retour du serveur.','warning')}`;footer=button('Confirmer la remise','explain',{tone:'primary',disabled:blocked()});}
 else if(ui.modal==='loyalty'||ui.modal==='qr'){title='Fidélité';body=`<div class="qr-slot">${icon('qr')}<strong>Emplacement du QR réel</strong><small>Le studio ne fabrique pas de jeton de fidélité.</small></div>${input('Rechercher un membre','','search')}${notice('Conserver le parcours existant','Lecture QR, identité, consentements et crédits restent sous le contrôle métier.')}`;footer=button('Voir la carte client','screen',{value:'loyalty-card',tone:'primary'});}
 else if(ui.modal==='note'){title='Note de préparation';body=`<div class="sm-field"><label for="note-text">Votre note</label><textarea id="note-text" placeholder="Ex. sauces à part">${esc(ui.note??'')}</textarea></div>`;footer=button('Conserver la note de maquette','save-note',{tone:'primary'});}
 else if(ui.modal==='payment'){title='Encaissement';body=notice('Aucun paiement réel','Ce bouton illustre l’entrée du parcours. Aucun terminal ni prestataire n’est contacté.');footer=button('Voir l’écran de règlement','screen',{value:'pos-payment',tone:'primary'});}
 else if(ui.modal==='clear'){title='Vider le ticket ?';body='<p>Cette action vide seulement les données fictives du studio. Elle n’est pas un remboursement.</p>';footer=button('Vider le ticket de démonstration','confirm-clear',{tone:'danger'});}
 else if(ui.modal==='navigation'){title='Application de navigation';body=`<div class="stack">${['Plans','Google Maps','Waze'].map(n=>button(n,'explain',{icon:'pin'})).join('')}</div><p>Les liens de navigation réels ne sont pas ouverts depuis les adresses fictives.</p>`;}
 else if(ui.modal==='filters'){title='Filtres';body=`<div class="stack">${input('Recherche')}${input('Date','','date')}<div class="sm-field"><label>Statut<select><option>Tous</option><option>En cours</option><option>Terminé</option></select></label></div></div>`;footer=button('Fermer les filtres de maquette','close',{tone:'primary'});}
 else {title=ui.modal==='assign'?'Affecter une mission':'Détail de présentation';body=`${notice('Présentation uniquement','Les actions réelles seront reconnectées à leurs callbacks existants, sans nouvelle règle métier.')}<div class="stack">${input('Libellé','Démonstration')}${input('Note')}</div>`;footer=button('Fermer','close');}
 return `<dialog id="studio-dialog" class="sm-dialog" aria-labelledby="dialog-title"><div class="sm-sheet"><header class="sm-sheet-head"><h2 id="dialog-title">${esc(title)}</h2>${iconButton('close','Fermer la fenêtre','close')}</header><div class="sm-sheet-body">${body}</div>${footer?`<footer class="sm-sheet-foot">${footer}</footer>`:''}</div></dialog>`;
}
function toast(message){let el=document.getElementById('toast');if(el){el.textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.textContent='';},4500);}}
let dialogReturnFocus=null;
function restoreDialogFocus(){
 if(!dialogReturnFocus)return;
 const nodes=[...document.querySelectorAll('[data-action]')];
 const el=nodes.find(n=>n.dataset.action===dialogReturnFocus.action&&n.dataset.value===dialogReturnFocus.value&&n.getAttribute('aria-label')===dialogReturnFocus.label);
 el?.focus({preventScroll:true});dialogReturnFocus=null;
}
function render(){
 const previous=document.activeElement,focusId=previous?.id,selection=previous instanceof HTMLInputElement&&['text','search'].includes(previous.type)?previous.selectionStart:null;
 const oldDialog=document.getElementById('studio-dialog');if(oldDialog?.open)oldDialog.close();
 document.body.style.cssText=cssVariables(ui.theme,ui.accent);document.body.dataset.theme=ui.theme;document.body.dataset.reducedMotion=String(ui.reduced);document.body.dataset.reduceTransparency=String(!ui.transparent);document.title=`${selected().title} · Snack Manager Design Studio`;
 document.getElementById('app').innerHTML=toolbar()+content()+`<footer class="studio-meta"><span>Maquette · données fictives · aucune opération réelle</span><span>${esc(selected().family)} / ${esc(selected().title)} · ${screens.length} vues de référence</span></footer>`+(ui.modal?modalContent():'')+'<div id="toast" class="toast" role="status"></div>';
 updateMetrics();
 if(ui.modal){const dialog=document.getElementById('studio-dialog');dialog.showModal();dialog.addEventListener('cancel',e=>{e.preventDefault();ui.modal=null;render();restoreDialogFocus();});}
 else if(focusId){const next=document.getElementById(focusId);next?.focus({preventScroll:true});if(selection!==null&&next instanceof HTMLInputElement)next.setSelectionRange(selection,selection);}
}
function updateMetrics(){document.body.style.setProperty('--studio-h',(document.querySelector('.studio-bar')?.offsetHeight??0)+'px');document.body.style.setProperty('--state-h',(document.querySelector('.state-strip')?.offsetHeight??0)+'px');}
window.addEventListener('resize',updateMetrics);
function go(id){if(!screens.some(s=>s.id===id))return;ui.screen=id;ui.query='';ui.category='Tous';ui.cartOpen=false;ui.modal=['pos-config','online-product'].includes(id)?'product':id==='pos-loyalty'?'loyalty':null;try{history.replaceState(null,'','#'+id);}catch{}render();window.scrollTo(0,0);}
document.addEventListener('click',e=>{
 const target=e.target instanceof Element?e.target.closest('[data-action]'):null;if(!target||target.disabled)return;const action=target.dataset.action,value=target.dataset.value;
 if(action==='screen'){go(value);return;}
 const wasModal=!!ui.modal;
 if(!wasModal)dialogReturnFocus={action,value,label:target.getAttribute('aria-label')};
 if(action==='theme')ui.theme=ui.theme==='light'?'dark':'light';
 else if(action==='theme-light')ui.theme='light';else if(action==='theme-dark')ui.theme='dark';
 else if(action==='accent')ui.accent=ui.accent===brand.preview?brand.snackManager:brand.preview;
 else if(action==='motion')ui.reduced=!ui.reduced;
 else if(action==='category')ui.category=value;
 else if(action==='order-mode')ui.mode=value;
 else if(action==='checkout-mode')ui.checkoutMode=value;
 else if(action==='cart')ui.cartOpen=!ui.cartOpen;
 else if(action==='channel')ui.channel=value;
 else if(action==='kds-tab')ui.kdsTab=value;
 else if(action==='allday')ui.allDay=!ui.allDay;
 else if(action==='product'){ui.product=value;ui.modal='product';}
 else if(action==='add'){if(blocked())return;const existing=ui.cart.find(l=>l.id===value);if(existing)existing.qty+=1;else ui.cart.push({id:value,qty:1});ui.modal=null;}
 else if(action==='increment'){const l=ui.cart.find(l=>l.id===value);if(l)l.qty=Math.min(99,l.qty+1);}
 else if(action==='decrement'){const l=ui.cart.find(l=>l.id===value);if(l)l.qty-=1;ui.cart=ui.cart.filter(l=>l.qty>0);}
 else if(action==='advance'){if(blocked())return;const t=tickets.find(t=>String(t.number)===value);if(t)t.status=t.status==='new'?'preparing':'ready';}
 else if(action==='confirm-clear') {ui.cart=[];ui.modal=null;}
 else if(action==='save-note'){ui.note=document.getElementById('note-text')?.value??'';ui.modal=null;}
 else if(action==='close'){ui.modal=null;}
 else if(action==='pin'){if(value==='Effacer')ui.pin=ui.pin.slice(0,-1);else if(value==='Entrer'){toast('Identification non active dans la maquette.');return;}else if(ui.pin.length<4)ui.pin+=value;}
 else if(action==='search-tab'){go('online-menu');document.getElementById('product-search')?.focus();return;}
 else if(action==='scan-result'){toast('Lecture illustrative : attendre la confirmation du serveur avant toute attribution.');return;}
 else if(action==='table-filter'){target.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('active'));target.classList.add('active');toast('Sélection visuelle uniquement : le filtre réel reste piloté par la page existante.');return;}
 else if(action==='export'){const data='maquette,donnees_reelles\nSnack Manager,non\n';const url=URL.createObjectURL(new Blob([data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='maquette-exemple.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}
 else if(action==='explain'||action==='park'){toast('Maquette uniquement : aucune écriture dans le restaurant.');return;}
 else ui.modal=action;
 render();
 if(wasModal&&!ui.modal)restoreDialogFocus();
});
document.addEventListener('input',e=>{
 if(e.target.id==='product-search'){ui.query=e.target.value;render();}
 else if(e.target.id==='table-search'){const q=e.target.value.toLowerCase();document.querySelectorAll('tbody tr').forEach(tr=>{tr.hidden=!tr.textContent.toLowerCase().includes(q);});}
});
document.addEventListener('change',e=>{
 if(e.target.id==='screen-select')go(e.target.value);
 if(e.target.id==='state-select'){ui.state=e.target.value;render();}
 if(e.target.id==='motion-check'){ui.reduced=e.target.checked;render();}
 if(e.target.id==='transparency-check'){ui.transparent=!e.target.checked;render();}
});
document.addEventListener('submit',e=>{e.preventDefault();toast('Aucune donnée n’est envoyée.');});
const requested=location.hash.slice(1)||new URLSearchParams(location.search).get('screen')||document.body.dataset.start;
if(requested&&screens.some(s=>s.id===requested))ui.screen=requested;
if(matchMedia('(prefers-reduced-motion: reduce)').matches)ui.reduced=true;
if(['pos-config','online-product'].includes(ui.screen))ui.modal='product';if(ui.screen==='pos-loyalty')ui.modal='loyalty';render();
